version = 1

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "github.com/brevity-engine/ansible"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "java"
enabled = true

[analyzers.meta]
runtime_version = "10"

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["vue"]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "scalafmt"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true
